# Generated by Django 4.2.25 on 2025-10-17 18:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("message", models.TextField(verbose_name="message")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("transaction", "Transaction"),
                            ("payment", "Payment"),
                            ("security", "Security"),
                            ("kyc", "KYC"),
                            ("gas", "Gas Sponsorship"),
                            ("marketing", "Marketing"),
                            ("system", "System"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="notification type",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(db_index=True, default=False, verbose_name="is read"),
                ),
                ("read_at", models.DateTimeField(blank=True, null=True, verbose_name="read at")),
                (
                    "action_url",
                    models.URLField(
                        blank=True,
                        help_text="Deep link or URL for action",
                        max_length=500,
                        verbose_name="action URL",
                    ),
                ),
                (
                    "action_text",
                    models.CharField(
                        blank=True,
                        help_text="Text for action button",
                        max_length=100,
                        verbose_name="action text",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data (tx_hash, payment_id, etc.)",
                        verbose_name="metadata",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon name or emoji",
                        max_length=50,
                        verbose_name="icon",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, max_length=500, verbose_name="image URL"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="expires at"),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "push_enabled",
                    models.BooleanField(default=True, verbose_name="push notifications"),
                ),
                (
                    "email_enabled",
                    models.BooleanField(default=True, verbose_name="email notifications"),
                ),
                (
                    "sms_enabled",
                    models.BooleanField(default=False, verbose_name="SMS notifications"),
                ),
                (
                    "transaction_notifications",
                    models.BooleanField(default=True, verbose_name="transaction notifications"),
                ),
                (
                    "payment_notifications",
                    models.BooleanField(default=True, verbose_name="payment notifications"),
                ),
                (
                    "security_notifications",
                    models.BooleanField(default=True, verbose_name="security notifications"),
                ),
                (
                    "kyc_notifications",
                    models.BooleanField(default=True, verbose_name="KYC notifications"),
                ),
                (
                    "gas_notifications",
                    models.BooleanField(default=True, verbose_name="gas notifications"),
                ),
                (
                    "marketing_notifications",
                    models.BooleanField(default=False, verbose_name="marketing notifications"),
                ),
                ("dnd_enabled", models.BooleanField(default=False, verbose_name="Do Not Disturb")),
                (
                    "dnd_start_time",
                    models.TimeField(blank=True, null=True, verbose_name="DND start time"),
                ),
                (
                    "dnd_end_time",
                    models.TimeField(blank=True, null=True, verbose_name="DND end time"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
            ],
            options={
                "verbose_name": "notification preference",
                "verbose_name_plural": "notification preferences",
            },
        ),
        migrations.CreateModel(
            name="PushToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True, max_length=255, unique=True, verbose_name="push token"
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[("ios", "iOS"), ("android", "Android"), ("web", "Web")],
                        max_length=10,
                        verbose_name="device type",
                    ),
                ),
                (
                    "device_name",
                    models.CharField(blank=True, max_length=255, verbose_name="device name"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="is active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("last_used_at", models.DateTimeField(auto_now=True, verbose_name="last used at")),
            ],
            options={
                "verbose_name": "push token",
                "verbose_name_plural": "push tokens",
                "ordering": ["-last_used_at"],
            },
        ),
    ]
