# Generated by Django 4.2.25 on 2025-10-17 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "eoa_address",
                    models.CharField(
                        db_index=True,
                        help_text="Externally Owned Account address (0x...)",
                        max_length=42,
                        unique=True,
                        verbose_name="EOA address",
                    ),
                ),
                (
                    "smart_account_address",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ERC-4337 Smart Account address (0x...)",
                        max_length=42,
                        null=True,
                        unique=True,
                        verbose_name="smart account address",
                    ),
                ),
                (
                    "chain_id",
                    models.IntegerField(
                        db_index=True,
                        help_text="Blockchain chain ID (1=Ethereum, 8453=Base, etc.)",
                        verbose_name="chain ID",
                    ),
                ),
                (
                    "network",
                    models.CharField(
                        choices=[
                            ("ethereum", "Ethereum"),
                            ("base", "Base"),
                            ("arbitrum", "Arbitrum"),
                            ("optimism", "Optimism"),
                            ("polygon", "Polygon"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="network",
                    ),
                ),
                (
                    "is_smart_account_deployed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the smart account contract is deployed on-chain",
                        verbose_name="smart account deployed",
                    ),
                ),
                (
                    "deployment_tx_hash",
                    models.CharField(
                        blank=True,
                        help_text="Transaction hash of smart account deployment",
                        max_length=66,
                        verbose_name="deployment transaction hash",
                    ),
                ),
                (
                    "wallet_name",
                    models.CharField(
                        blank=True,
                        help_text="User-defined wallet name",
                        max_length=100,
                        verbose_name="wallet name",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Primary wallet for this user on this network",
                        verbose_name="is primary",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="is active")),
                (
                    "is_backed_up",
                    models.BooleanField(
                        default=False,
                        help_text="Whether user has backed up seed phrase/private key",
                        verbose_name="is backed up",
                    ),
                ),
                (
                    "backup_reminder_sent",
                    models.BooleanField(default=False, verbose_name="backup reminder sent"),
                ),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="metadata")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "last_used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="last used at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "wallet",
                "verbose_name_plural": "wallets",
                "ordering": ["-is_primary", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WalletBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "token_symbol",
                    models.CharField(
                        db_index=True,
                        help_text="Token symbol (ETH, USDC, USDT, etc.)",
                        max_length=20,
                        verbose_name="token symbol",
                    ),
                ),
                (
                    "token_address",
                    models.CharField(
                        blank=True,
                        help_text="Token contract address (empty for native token)",
                        max_length=42,
                        verbose_name="token address",
                    ),
                ),
                ("token_decimals", models.IntegerField(default=18, verbose_name="token decimals")),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=18,
                        default=0,
                        help_text="Token balance in smallest unit",
                        max_digits=36,
                        verbose_name="balance",
                    ),
                ),
                (
                    "balance_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Balance in USD equivalent",
                        max_digits=20,
                        verbose_name="balance USD",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, db_index=True, verbose_name="last updated"),
                ),
                (
                    "is_stale",
                    models.BooleanField(
                        default=False,
                        help_text="Whether balance needs refresh",
                        verbose_name="is stale",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balances",
                        to="wallets.wallet",
                        verbose_name="wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "wallet balance",
                "verbose_name_plural": "wallet balances",
                "ordering": ["-balance_usd"],
                "indexes": [
                    models.Index(
                        fields=["wallet", "token_symbol"], name="wallets_wal_wallet__71ebbf_idx"
                    ),
                    models.Index(
                        fields=["wallet", "-balance_usd"], name="wallets_wal_wallet__47dfaf_idx"
                    ),
                    models.Index(fields=["-last_updated"], name="wallets_wal_last_up_1e691c_idx"),
                ],
                "unique_together": {("wallet", "token_symbol")},
            },
        ),
        migrations.CreateModel(
            name="WalletActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("created", "Wallet Created"),
                            ("smart_account_deployed", "Smart Account Deployed"),
                            ("transaction", "Transaction"),
                            ("balance_check", "Balance Check"),
                            ("backup", "Backup Performed"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="activity type",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="description")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="metadata")),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True, verbose_name="IP address"),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="user agent")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="wallets.wallet",
                        verbose_name="wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "wallet activity",
                "verbose_name_plural": "wallet activities",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["wallet", "-created_at"], name="wallets_wal_wallet__9fd38f_idx"
                    ),
                    models.Index(
                        fields=["activity_type", "-created_at"],
                        name="wallets_wal_activit_11e247_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="wallet",
            index=models.Index(fields=["user", "chain_id"], name="wallets_wal_user_id_360aca_idx"),
        ),
        migrations.AddIndex(
            model_name="wallet",
            index=models.Index(fields=["eoa_address"], name="wallets_wal_eoa_add_6c5d4a_idx"),
        ),
        migrations.AddIndex(
            model_name="wallet",
            index=models.Index(
                fields=["smart_account_address"], name="wallets_wal_smart_a_cd41e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wallet",
            index=models.Index(
                fields=["user", "is_primary"], name="wallets_wal_user_id_e48106_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wallet",
            index=models.Index(fields=["-created_at"], name="wallets_wal_created_1180bb_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="wallet",
            unique_together={("user", "chain_id", "eoa_address")},
        ),
    ]
