# Generated by Django 4.2.25 on 2025-10-17 18:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "tx_hash",
                    models.CharField(
                        db_index=True,
                        help_text="Blockchain transaction hash",
                        max_length=66,
                        unique=True,
                        verbose_name="transaction hash",
                    ),
                ),
                (
                    "tx_type",
                    models.CharField(
                        choices=[
                            ("send", "Send"),
                            ("receive", "Receive"),
                            ("swap", "Swap"),
                            ("payment", "Payment"),
                            ("gas_refund", "Gas Refund"),
                            ("smart_account_deploy", "Smart Account Deploy"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="transaction type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("replaced", "Replaced"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "from_address",
                    models.CharField(db_index=True, max_length=42, verbose_name="from address"),
                ),
                (
                    "to_address",
                    models.CharField(db_index=True, max_length=42, verbose_name="to address"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=18,
                        help_text="Transaction amount in token units",
                        max_digits=36,
                        verbose_name="amount",
                    ),
                ),
                (
                    "token_symbol",
                    models.CharField(db_index=True, max_length=20, verbose_name="token symbol"),
                ),
                (
                    "token_address",
                    models.CharField(
                        blank=True,
                        help_text="Token contract address (empty for native token)",
                        max_length=42,
                        verbose_name="token address",
                    ),
                ),
                (
                    "amount_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="amount USD",
                    ),
                ),
                (
                    "gas_limit",
                    models.BigIntegerField(blank=True, null=True, verbose_name="gas limit"),
                ),
                (
                    "gas_used",
                    models.BigIntegerField(blank=True, null=True, verbose_name="gas used"),
                ),
                (
                    "gas_price",
                    models.BigIntegerField(blank=True, null=True, verbose_name="gas price (wei)"),
                ),
                (
                    "gas_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=18,
                        help_text="Total gas fee in native token",
                        max_digits=36,
                        null=True,
                        verbose_name="gas fee",
                    ),
                ),
                (
                    "gas_sponsored",
                    models.BooleanField(
                        default=False,
                        help_text="Whether gas was sponsored by paymaster",
                        verbose_name="gas sponsored",
                    ),
                ),
                (
                    "block_number",
                    models.BigIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="block number"
                    ),
                ),
                (
                    "block_timestamp",
                    models.DateTimeField(blank=True, null=True, verbose_name="block timestamp"),
                ),
                ("confirmations", models.IntegerField(default=0, verbose_name="confirmations")),
                ("chain_id", models.IntegerField(db_index=True, verbose_name="chain ID")),
                ("network", models.CharField(max_length=20, verbose_name="network")),
                ("nonce", models.BigIntegerField(blank=True, null=True, verbose_name="nonce")),
                ("input_data", models.TextField(blank=True, verbose_name="input data")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="metadata")),
                ("error_message", models.TextField(blank=True, verbose_name="error message")),
                ("failure_reason", models.TextField(blank=True, verbose_name="failure reason")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "confirmed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="confirmed at"),
                ),
                (
                    "replaced_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replaces",
                        to="transactions.transaction",
                        verbose_name="replaced by",
                    ),
                ),
            ],
            options={
                "verbose_name": "transaction",
                "verbose_name_plural": "transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
