# Generated by Copilot on 2025-01-13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chain_id', models.PositiveBigIntegerField(db_index=True)),
                ('sender', models.CharField(db_index=True, max_length=42)),
                ('user_op_hash', models.CharField(max_length=66, unique=True)),
                ('nonce', models.CharField(max_length=120)),
                ('call_data', models.BinaryField(blank=True, null=True)),
                ('call_gas_limit', models.BigIntegerField(default=0)),
                ('verification_gas_limit', models.BigIntegerField(default=0)),
                ('pre_verification_gas', models.BigIntegerField(default=0)),
                ('max_fee_per_gas', models.BigIntegerField(default=0)),
                ('max_priority_fee_per_gas', models.BigIntegerField(default=0)),
                ('paymaster', models.CharField(blank=True, max_length=42)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('dispatched', 'Dispatched'), ('included', 'Included'), ('failed', 'Failed'), ('dropped', 'Dropped')], db_index=True, default='queued', max_length=32)),
                ('failure_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('queued_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_operations', to='wallets.wallet')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-queued_at'],
            },
        ),
        migrations.CreateModel(
            name='BundlerJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_endpoint', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('dispatching', 'Dispatching'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('retrying', 'Retrying')], db_index=True, default='queued', max_length=32)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('last_error', models.TextField(blank=True)),
                ('enqueued_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='bundler.useroperation')),
            ],
            options={
                'ordering': ['priority', 'enqueued_at'],
            },
        ),
        migrations.CreateModel(
            name='UserOperationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='bundler.useroperation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='useroperationevent',
            index=models.Index(fields=['event_type', 'created_at'], name='bundler_use_event__28c677_idx'),
        ),
        migrations.AddIndex(
            model_name='bundlerjob',
            index=models.Index(fields=['status', 'priority'], name='bundler_job_status_7ea6bd_idx'),
        ),
        migrations.AddIndex(
            model_name='bundlerjob',
            index=models.Index(fields=['enqueued_at'], name='bundler_job_enqueue_5a9cd5_idx'),
        ),
        migrations.AddIndex(
            model_name='useroperation',
            index=models.Index(fields=['chain_id', 'status'], name='bundler_use_chain_i_8521a2_idx'),
        ),
        migrations.AddIndex(
            model_name='useroperation',
            index=models.Index(fields=['queued_at'], name='bundler_use_queued__2e8c95_idx'),
        ),
    ]
