# Generated by Django 4.2.25 on 2025-10-18 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bundler", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="bundlerjob",
            new_name="bundler_bun_status_89fec0_idx",
            old_name="bundler_job_status_7ea6bd_idx",
        ),
        migrations.RenameIndex(
            model_name="bundlerjob",
            new_name="bundler_bun_enqueue_087e9d_idx",
            old_name="bundler_job_enqueue_5a9cd5_idx",
        ),
        migrations.RenameIndex(
            model_name="useroperation",
            new_name="bundler_use_chain_i_61ac7e_idx",
            old_name="bundler_use_chain_i_8521a2_idx",
        ),
        migrations.RenameIndex(
            model_name="useroperation",
            new_name="bundler_use_queued__585d5a_idx",
            old_name="bundler_use_queued__2e8c95_idx",
        ),
        migrations.RenameIndex(
            model_name="useroperationevent",
            new_name="bundler_use_event_t_63be08_idx",
            old_name="bundler_use_event__28c677_idx",
        ),
    ]
