# Generated by Django 4.2.25 on 2025-10-17 18:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KYCVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "tier",
                    models.IntegerField(
                        choices=[(1, "Basic"), (2, "Enhanced"), (3, "Premium")],
                        db_index=True,
                        verbose_name="KYC tier",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_review", "In Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="full name")),
                ("date_of_birth", models.DateField(verbose_name="date of birth")),
                ("nationality", models.CharField(max_length=100, verbose_name="nationality")),
                ("address", models.TextField(verbose_name="address")),
                ("city", models.CharField(max_length=100, verbose_name="city")),
                ("state", models.CharField(max_length=100, verbose_name="state/province")),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=20, verbose_name="postal code"),
                ),
                ("country", models.CharField(max_length=100, verbose_name="country")),
                (
                    "id_type",
                    models.CharField(
                        help_text="NIN, BVN, Passport, Driver License, etc.",
                        max_length=50,
                        verbose_name="ID type",
                    ),
                ),
                ("id_number", models.CharField(max_length=100, verbose_name="ID number")),
                (
                    "bvn",
                    models.CharField(
                        blank=True,
                        help_text="Bank Verification Number",
                        max_length=11,
                        verbose_name="BVN",
                    ),
                ),
                ("bvn_verified", models.BooleanField(default=False, verbose_name="BVN verified")),
                (
                    "documents",
                    models.JSONField(
                        default=dict,
                        help_text="Document URLs and metadata",
                        verbose_name="documents",
                    ),
                ),
                (
                    "selfie_url",
                    models.URLField(blank=True, max_length=500, verbose_name="selfie URL"),
                ),
                (
                    "liveness_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Liveness detection score (0-100)",
                        max_digits=5,
                        null=True,
                        verbose_name="liveness score",
                    ),
                ),
                (
                    "face_match_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Face matching score (0-100)",
                        max_digits=5,
                        null=True,
                        verbose_name="face match score",
                    ),
                ),
                (
                    "risk_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Overall risk score (0-100)",
                        max_digits=5,
                        null=True,
                        verbose_name="risk score",
                    ),
                ),
                (
                    "verification_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Data from verification provider",
                        verbose_name="verification data",
                    ),
                ),
                ("review_notes", models.TextField(blank=True, verbose_name="review notes")),
                ("rejection_reason", models.TextField(blank=True, verbose_name="rejection reason")),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="submitted at"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="reviewed at"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="approved at"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="expires at"),
                ),
            ],
            options={
                "verbose_name": "KYC verification",
                "verbose_name_plural": "KYC verifications",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
