# Generated by Django 4.2.25 on 2025-10-17 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("kyc", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="kycverification",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_kyc",
                to=settings.AUTH_USER_MODEL,
                verbose_name="reviewer",
            ),
        ),
        migrations.AddField(
            model_name="kycverification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kyc_verifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddIndex(
            model_name="kycverification",
            index=models.Index(
                fields=["user", "-submitted_at"], name="kyc_kycveri_user_id_bc4115_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kycverification",
            index=models.Index(fields=["tier", "status"], name="kyc_kycveri_tier_e2b775_idx"),
        ),
        migrations.AddIndex(
            model_name="kycverification",
            index=models.Index(
                fields=["status", "-submitted_at"], name="kyc_kycveri_status_022a9c_idx"
            ),
        ),
    ]
