# Generated by Django 4.2.25 on 2025-10-17 18:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GasSponsorship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("chain_id", models.IntegerField(db_index=True, verbose_name="chain ID")),
                (
                    "daily_limit",
                    models.BigIntegerField(
                        help_text="Daily gas limit in wei", verbose_name="daily limit"
                    ),
                ),
                (
                    "used_today",
                    models.BigIntegerField(
                        default=0, help_text="Gas used today in wei", verbose_name="used today"
                    ),
                ),
                (
                    "kyc_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Multiplier based on KYC tier",
                        max_digits=4,
                        verbose_name="KYC multiplier",
                    ),
                ),
                (
                    "last_reset_date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="last reset date",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="is active")),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Verified on-chain with paymaster",
                        verbose_name="is verified",
                    ),
                ),
                (
                    "total_gas_sponsored",
                    models.BigIntegerField(
                        default=0,
                        help_text="Total gas sponsored lifetime (wei)",
                        verbose_name="total gas sponsored",
                    ),
                ),
                (
                    "transactions_sponsored",
                    models.IntegerField(default=0, verbose_name="transactions sponsored"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
            ],
            options={
                "verbose_name": "gas sponsorship",
                "verbose_name_plural": "gas sponsorships",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GasSponsorshipHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "gas_amount",
                    models.BigIntegerField(
                        help_text="Gas amount sponsored in wei", verbose_name="gas amount"
                    ),
                ),
                (
                    "gas_price",
                    models.BigIntegerField(
                        help_text="Gas price at time of sponsorship (wei)", verbose_name="gas price"
                    ),
                ),
                (
                    "gas_cost_native",
                    models.DecimalField(
                        decimal_places=18, max_digits=36, verbose_name="gas cost (native token)"
                    ),
                ),
                (
                    "gas_cost_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="gas cost (USD)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "sponsorship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="gas_sponsorship.gassponsorship",
                        verbose_name="sponsorship",
                    ),
                ),
            ],
            options={
                "verbose_name": "gas sponsorship history",
                "verbose_name_plural": "gas sponsorship histories",
                "ordering": ["-created_at"],
            },
        ),
    ]
