# Generated by Django 4.2.25 on 2025-10-17 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gas_sponsorship", "0001_initial"),
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gassponsorshiphistory",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gas_sponsorship_history",
                to="transactions.transaction",
                verbose_name="transaction",
            ),
        ),
    ]
