# Generated by Django 4.2.25 on 2025-10-17 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gas_sponsorship", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gassponsorship",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gas_sponsorships",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddIndex(
            model_name="gassponsorshiphistory",
            index=models.Index(
                fields=["sponsorship", "-created_at"], name="gas_sponsor_sponsor_205d55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gassponsorshiphistory",
            index=models.Index(fields=["transaction"], name="gas_sponsor_transac_3dee4e_idx"),
        ),
        migrations.AddIndex(
            model_name="gassponsorship",
            index=models.Index(fields=["user", "chain_id"], name="gas_sponsor_user_id_4930af_idx"),
        ),
        migrations.AddIndex(
            model_name="gassponsorship",
            index=models.Index(fields=["last_reset_date"], name="gas_sponsor_last_re_d380ad_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="gassponsorship",
            unique_together={("user", "chain_id")},
        ),
    ]
