# Generated by Copilot on 2025-01-13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gas_sponsorship', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymasterBudgetSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chain_id', models.PositiveBigIntegerField(db_index=True, verbose_name='chain ID')),
                ('paymaster_address', models.CharField(db_index=True, max_length=42, verbose_name='paymaster address')),
                ('native_balance_wei', models.BigIntegerField(default=0, verbose_name='native balance (wei)')),
                ('entry_point_deposit_wei', models.BigIntegerField(default=0, verbose_name='entry point deposit (wei)')),
                ('estimated_daily_burn_wei', models.BigIntegerField(default=0, verbose_name='estimated 24h burn (wei)')),
                ('block_number', models.BigIntegerField(blank=True, null=True, verbose_name='block number')),
                ('observed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='observed at')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
            ],
            options={
                'verbose_name': 'paymaster budget snapshot',
                'verbose_name_plural': 'paymaster budget snapshots',
                'ordering': ['-observed_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymasterReplenishmentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chain_id', models.PositiveBigIntegerField(db_index=True, verbose_name='chain ID')),
                ('paymaster_address', models.CharField(max_length=42, verbose_name='paymaster address')),
                ('amount_wei', models.BigIntegerField(verbose_name='amount (wei)')),
                ('direction', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')], default='deposit', max_length=16, verbose_name='direction')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('executing', 'Executing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16, verbose_name='status')),
                ('latest_error', models.TextField(blank=True, verbose_name='latest error')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='context')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name='paymaster_replenishment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'paymaster replenishment request',
                'verbose_name_plural': 'paymaster replenishment requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymasterbudgetsnapshot',
            index=models.Index(fields=['paymaster_address', '-observed_at'], name='gas_sponsor_paymast_dfab4d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymasterbudgetsnapshot',
            index=models.Index(fields=['chain_id', 'observed_at'], name='gas_sponsor_chain_i_bdaac4_idx'),
        ),
        migrations.AddIndex(
            model_name='paymasterreplenishmentrequest',
            index=models.Index(fields=['status', 'created_at'], name='gas_sponsor_status__a713ad_idx'),
        ),
        migrations.AddIndex(
            model_name='paymasterreplenishmentrequest',
            index=models.Index(fields=['paymaster_address', 'status'], name='gas_sponsor_paymast_90f87d_idx'),
        ),
    ]
