# Generated by Django 4.2.25 on 2025-10-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gas_sponsorship", "0004_paymaster_controller"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="paymasterbudgetsnapshot",
            new_name="gas_sponsor_paymast_9ddbe3_idx",
            old_name="gas_sponsor_paymast_dfab4d_idx",
        ),
        migrations.RenameIndex(
            model_name="paymasterbudgetsnapshot",
            new_name="gas_sponsor_chain_i_ce12a9_idx",
            old_name="gas_sponsor_chain_i_bdaac4_idx",
        ),
        migrations.RenameIndex(
            model_name="paymasterreplenishmentrequest",
            new_name="gas_sponsor_status_391ea9_idx",
            old_name="gas_sponsor_status__a713ad_idx",
        ),
        migrations.RenameIndex(
            model_name="paymasterreplenishmentrequest",
            new_name="gas_sponsor_paymast_0db556_idx",
            old_name="gas_sponsor_paymast_90f87d_idx",
        ),
        migrations.AlterField(
            model_name="paymasterreplenishmentrequest",
            name="paymaster_address",
            field=models.CharField(db_index=True, max_length=42, verbose_name="paymaster address"),
        ),
    ]
