# Generated by Django 4.2.25 on 2025-10-17 18:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("airtime", "Airtime"),
                            ("electricity", "Electricity"),
                            ("cable_tv", "Cable TV"),
                            ("internet", "Internet"),
                            ("water", "Water"),
                            ("transfer", "Bank Transfer"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="payment type",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        help_text="Service provider (MTN, IKEDC, DSTV, etc.)",
                        max_length=100,
                        verbose_name="provider",
                    ),
                ),
                (
                    "recipient_id",
                    models.CharField(
                        help_text="Phone number, meter number, smartcard number, etc.",
                        max_length=100,
                        verbose_name="recipient ID",
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(blank=True, max_length=255, verbose_name="recipient name"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Payment amount in NGN",
                        max_digits=12,
                        verbose_name="amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="NGN", max_length=3, verbose_name="currency"),
                ),
                (
                    "reference",
                    models.CharField(
                        db_index=True,
                        help_text="Unique payment reference",
                        max_length=100,
                        unique=True,
                        verbose_name="reference",
                    ),
                ),
                (
                    "provider_reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference from payment provider",
                        max_length=100,
                        verbose_name="provider reference",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "package_name",
                    models.CharField(
                        blank=True,
                        help_text="For cable TV, internet packages",
                        max_length=200,
                        verbose_name="package name",
                    ),
                ),
                (
                    "package_code",
                    models.CharField(blank=True, max_length=100, verbose_name="package code"),
                ),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="metadata")),
                (
                    "provider_response",
                    models.JSONField(blank=True, default=dict, verbose_name="provider response"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="error message")),
                ("failure_reason", models.TextField(blank=True, verbose_name="failure reason")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="completed at"),
                ),
            ],
            options={
                "verbose_name": "payment",
                "verbose_name_plural": "payments",
                "ordering": ["-created_at"],
            },
        ),
    ]
