# Generated by Django 4.2.25 on 2025-10-17 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transactions", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked blockchain transaction for payment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="transactions.transaction",
                verbose_name="transaction",
            ),
        ),
    ]
